osx_image: xcode7
language: objective-c
xcode_project: BricBrac.xcodeproj
xcode_scheme: BricBrac
before_script:
  - echo "$HOME/cotsog/BricBrac/BricBrac.xcodeproj"
  - ls -al
  - /Applications/Xcode.app/Contents/MacOS/Xcode BricBrac.xcodeproj > /dev/null 2>&1 &
  - sleep 30
script:
  - xcodebuild test -project BricBrac.xcodeproj -sdk iphonesimulator -scheme BricBrac
