osx_image: xcode7
language: objective-c
xcode_project: BricBrac.xcodeproj
xcode_scheme: BricBrac
before_script:
  - /Applications/Xcode.app/Contents/MacOS/Xcode $HOME/build/cotsog/BricBrac/BricBrac.xcodeproj > /dev/null 2>&1 &
  - sleep 10
script:
  - xcodebuild test -project BricBrac.xcodeproj -sdk iphonesimulator -scheme BricBrac
