osx_image: xcode7
language: objective-c
xcode_project: BricBrac.xcodeproj
xcode_scheme: BricBrac
before_script:
  - /Applications/Xcode.app/Contents/MacOS/Xcode > /dev/null 2>&1 &
script:
  - xcodebuild test -project BricBrac.xcodeproj -sdk iphonesimulator -scheme BricBrac
